// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydzovxmiltwgsdgzcxfu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlkem92eG1pbHR3Z3NkZ3pjeGZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI5MzUxNjksImV4cCI6MjA3ODUxMTE2OX0.q2yBayAxhR6ESp2IYwu-wGyzHos9AE6Bhm59lMNmMhg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});